name: Lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Run clippy
        run: cargo clippy --release --all-targets --all-features -- -D warnings
      - name: Run rustfmt
        run: cargo fmt --check
