name: Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release:
    name: Build and release for Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Publish to crates.io
        env:
          CRATES_IO_TOKEN: ${{secrets.CRATES_IO_TOKEN}}
        run: |
          cargo test
          cargo test --release
          cargo publish --token ${CRATES_IO_TOKEN}